#!/bin/sh

tmux has-session -t deven
if [ $? != 0 ]
then
  tmux new-session   -s deven -d

  # set up editor
  tmux split-window  -t deven:0 -h -p 70
  tmux split-window  -t deven:0.0 -v
  tmux send-keys     -t deven:0.0 "cd" C-m
  tmux send-keys     -t deven:0.2 "cd" C-m
  tmux send-keys     -t deven:0.1 "cd" C-m
  tmux send-keys     -t deven:0.1 "vim" C-m

  # window 1
  tmux new-window    -t deven:1
  tmux split-window  -t deven:1 -h -p 70
  tmux send-keys     -t deven:1.0 "cd" C-m
  #tmux split-window  -t deven:1.1 -h
  #tmux send-keys     -t deven:1.1 "cd" C-m

  # window 2
  tmux new-window    -t deven:2
  tmux split-window  -t deven:2 -h -p 70
  tmux send-keys     -t deven:2.0 "cd" C-m
  #tmux split-window  -t deven:2.1 -h
  #tmux send-keys     -t deven:2.1 "cd" C-m

  #set window to first when session is open
  tmux select-window -t deven:0
fi
tmux attach -t deven
