#!/bin/sh

tmux has-session -t devfun
if [ $? != 0 ]
then
  tmux new-session   -s devfun -d

  # set up Blog folder
  tmux new-window    -t devfun:1 -n "blog"
  tmux send-keys     -t devfun:1.0 "cd ~/blog" C-m
  tmux split-window  -t devfun:1.0 -p 70 -h
  tmux send-keys     -t devfun:1.1 "cd ~/blog" C-m
  tmux send-keys     -t devfun:1.1 "vim" C-m
  tmux select-pane   -t devfun:1.0

  tmux new-window    -t devfun:2 -n "emfun"
  tmux send-keys     -t devfun:2.0 "cd ~/emfun" C-m
  tmux split-window  -t devfun:2.0 -p 70 -h
  tmux send-keys     -t devfun:2.1 "cd ~/emfun" C-m
  tmux send-keys     -t devfun:2.1 "vim" C-m
  tmux select-pane   -t devfun:2.0
 
  tmux new-window    -t devfun:3 -n "dotfiles"
  tmux send-keys     -t devfun:3.0 "cd ~/dotfiles" C-m
  tmux split-window  -t devfun:3.0 -p 70 -h
  tmux send-keys     -t devfun:3.1 "cd ~/dotfiles" C-m
  tmux send-keys     -t devfun:3.1 "vim" C-m
  tmux select-pane   -t devfun:3.0

  tmux select-window -t devfun:0
fi
tmux attach -t devfun
