#!/bin/sh

tmux has-session -t devfun
if [ $? != 0 ]
then
  tmux new-session   -s devfun -d

  # home window
  tmux split-window  -t devfun:0 -h
  tmux send-keys     -t devfun:0.0 "cd /Applications" C-m
  tmux send-keys     -t devfun:0.0 "ls" C-m
  tmux select-pane   -t devfun:0.0
  tmux send-keys     -t devfun:0.1 "cd" C-m

  # set up dev environment
  tmux new-window    -t devfun:1 -n "editor"
  tmux send-keys     -t devfun:1.0 "cd ~/projects" C-m
  tmux split-window  -t devfun:1.0 -p 70 -h
  tmux send-keys     -t devfun:1.1 "cd ~/projects" C-m
  tmux send-keys     -t devfun:1.1 "vim" C-m
  tmux select-pane   -t devfun:1.0
  
  #set window to first when session is open
  tmux select-window -t devfun:0
fi
tmux attach -t devfun
